.Dd May 26, 2014
.Dt GO-CAMO \&1 "GO-CAMO MANUAL"
.Os GO-CAMO VERSION
.Sh NAME
.Nm go-camo 
.Nd \&Go version of Camo server 
.Sh SYNOPSIS
.Nm go-camo
.Oo
.Em OPTIONS Ns 
.Oc
.Oo
.Em OPTION-ARGUMENTS Ns 
.Oc
.Sh DESCRIPTION
.Sy go-camo
is an implementation of Camo in Go.
.Pp
Camo is a special type of image proxy that proxies non-secure images over
SSL/TLS. This prevents mixed content warnings on secure pages.
.Pp
It works in conjunction with back-end code to rewrite image URLs and sign them
with an HMAC.
.Sh ENVIRONMENT VARS
.Bl -tag -width Ds
.It Sy GOCAMO_HMAC
The HMAC key to use.
.El
.Pp
.Em Note Ns 
: 
.Sx "OPTIONS" Ns
, if provided, override those defined in environment variables.
.Pp
For exmaple, if the HMAC key is provided on the command line, it will override
(if present), an HMAC key set in the environment var.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl k Ns , Fl -key Ns = Ns Aq Ar hmac-key
The HMAC key to use.
.It Fl H Ns , Fl -header Ns = Ns Aq Ar header
Extra header to return for each response. This option can be used multiple
times to add multiple headers.
.Pp
See 
.Sx "ADD_HEADERS"
for more info.
.It Fl -listen Ns = Ns Aq Ar address:port
Address and port to listen to, as a string of "address:port".
Default: "0.0.0.0:8080"
.It Fl -ssl-listen Ns = Ns Aq Ar address:port
Address and port to listen via SSL to, as a string of "address:port".
.It Fl -ssl-key Ns = Ns Aq Ar ssl-key-file
Path to ssl private key. Default: key.pem
.It Fl -ssl-cert Ns = Ns Aq Ar ssl-cert-file
Path to ssl certificate. Default: cert.pem
.It Fl -max-size Ns = Ns Aq Ar size
Max response image size in KB. Default: 5120
.It Fl -timeout Ns = Ns Aq Ar time
Timeout value for upstream response. Format is "4s" where 
.Em s
means seconds.
Default: 4s
.It Fl -max-redirects
Maximum number of redirects to follow. Default: 3
.It Fl -metrics
Enable prometheus compatible metrics endpoint.
.Pp
If metrics flag is provided, then the service will make a prometheus compatible
endpoint available at /metrics via HTTP GET.
.It Fl -no-log-ts
Do not add a timestamp to logging output.
.It Fl -no-fk
Disable frontend http keep-alive support.
.It Fl -no-bk
Disable backend http keep-alive support.
.It Fl -allow-content-video
Additionally allow "video/*" content type.
.It Fl -allow-credential-urls
Allow urls to contain user/pass credentials.
.It Fl -filter-ruleset Ns = Ns Aq Ar file
Path to a text file that contains a list (one per line) filter rules.
.Pp
If an filter-ruleset file is defined, that file is read and each line converted
into a filter rule. If the request fails the ruleset, the request is denied.
See
.Xr go-camo-filtering 5
for more information.
.It Fl -server-name Ns = Ns Aq Ar server-name
Value to use for the HTTP server field. Default: go-camo
.It Fl -expose-server-version
Include the server version in the HTTP server response header.
.It Fl -enable-xfwd4
Enable x-forwarded-for passthrough/generation.
.It Fl v Ns , Fl -verbose
Show verbose (debug) level log output
.It Fl V Ns , Fl -version
Print version and exit; specify twice to show license information
.It Fl h Ns , Fl -help
Show help output and exit
.El
.Sh ADD_HEADERS
Additional default headers (headers sent on every reply) can be set with the
.Fl H Ns , Fl -header
flag. This option can be used multiple times.
.Pp
The list of default headers sent are:
.Bd -literal
 X-Content-Type-Options: nosniff
 X-XSS-Protection: 1; mode=block
 Content-Security-Policy: default-src 'none'`
.Ed
.Pp
Additional headers are added to the above set.
.Pp
As an example, if you wanted to return an 
.Em Strict-Transport-Security
and an
.Em X-Frame-Options
header by default, you could add this to the command line:
.Bd -literal
 -H "Strict-Transport-Security: max-age=16070400" \\
 -H "X-Frame-Options: deny"
.Ed
.Sh EXAMPLES
Listen on loopback port 8080 with a upstream timeout of 6 seconds:
.Bd -literal
 go-camo -k BEEFBEEFBEEF --listen=127.0.0.1:8080 \e
   --timeout=6s 
.Ed
.Pp
Set HMAC key via env var, and an HSTS header:
.Bd -literal
 export GOCAMO_HMAC=BEEFBEEFBEEF
 go-camo --listen=127.0.0.1:8080 \e
   --timeout=6s \e
   -H "Strict-Transport-Security: max-age=16070400"
.Ed
.Sh WWW
.Bl -tag -width Ds
.It Lk https://github.com/cactus/go-camo
.El
.Sh SEE ALSO
.Bl -tag -width Ds
.It Lk https://github.com/atmos/camo
.El
