= go-camo-filtering(5)

:doctype: manpage
:release-version: 2.0.0
:man manual: Go-Camo Filtering Manual
:man source: Go-Camo {release-version}
:man-linkstyle: pass:[blue R < >]

== NAME

go-camo-filtering - Go-camo filtering information

== DESCRIPTION

go-camo(1) is an implementation of Camo in Go.

Go-camo accepts a filter for filtering as part of the *--filter-ruleset*
argument (see go-camo(1) for more info on arguments).

This document describes that syntax.

== MATCH_RULESETS

Each line of the ruleset file must adhere to the following format:

----
<RULE_TYPE>|<DOMAIN_COMPONENT|<URL_COMPONENT>
----

The components are as follows:

*__RULE_TYPE__*: _required_::
+
--
See _RULE_TYPE_ for more information.
--

*__DOMAIN_COMPONENT__*: _required_::
+
--
See _DOMAIN_COMPONENT_ for more information.
--

*__URL_COMPONENT__*: _optional_::
+
--
See _URL_COMPONENT_ for more information.
--

== RULE_TYPE

The *__RULE_TYPE__* component defines the filter type.

The supported types are:

*allow*::
+
--
This defines an allow filter. If any allow filters are defined, they take
precedence, and any request *NOT* matching this rule will be rejected.
--

*deny*::
+
--
This is a deny filter. Any request matching this this rule will be rejected.
--

== DOMAIN_COMPONENT

The domain component has the following format:

----
<DOMAIN_FLAGS>|<DOMAIN_MATCH_RULE>
----

The components are as follows:

*__DOMAIN_FLAGS__*: _optional_::
+
--
*s*::
    This means "include subdomains". This is similar to a `*.example.com` match
    except it also matches the base domain.
--

*__DOMAIN_MATCH_RULE__*: _required_::
+
--
The domain match rule is the glob match string for domain matching. A single
glob character may be used, to match to the left. Think of this as matching any
subdomains.  Partial component glob matches are not currently supported for
domain match rules. See _INVALID_EXAMPLES_ for more info.
--

.some examples
====
The following would match `example.com` as well as any subdomain, as the *s*
domain-flag is specified:

----
s|example.com
----

While the following here would only match sudomains of `example.com`, and
would not match the base domain itself:

----
|*.example.com
----
====

== URL_COMPONENT

The url component has the following format:

----
<URL_FLAG>|<URL_MATCH_RULE>
----

The components are as follows:

*__URL_FLAG__*: _optional_::
+
--
*i*::
This means the url component is to be compared case insensitively.
+
Please note that case insensitive comparisons are a bit slower. Benchmark for
large url lists.
--

*__URL_MATCH_RULE__*: _required_::
+
--
The url match rule is the glob match string for matching against the url path.
Glob characters match to the right.
--

.some examples
====
This would match `/foo/file.png` as well as `/fOo/FiLe.PnG`:

----
i|/foo/file.png
----

This would match any path ending in `/file.png`:

----
|*/file.png
----
====

== FULL_EXAMPLES

Here are some examples of full rulesets.

Match `example.com` and any subdomains, case insensitive url prefix match.

NOTE: Domain matches are always case insensitive!

----
deny|s|example.com|i|/some/subdir/*
----

Match any domain, with a case sensitive url suffix match:

----
deny||*||*/somebadfile.png
----

Reject everything from `bad.example.net`, including subdomains:

----
deny|s|bad.example.net||
----

== IDNA_NOTES

Any idna domains are internally converted to ascii/punycode and matched in that
format. This should make it safe to include unicode domains and have it match
either incoming format.

Thus the following should match both `bA1/4cher.example.com`, as well as
`xn--bcher-kva.example.com`.

----
deny||bA1/4cher.example.com||*
----

== OTHER_NOTES

*   Case insensitive components are stored twice in the tree, one for each
    character case. This can make for large trees.

*   Domains are always compared case insensitively (by lowercasing on input)
