.Dd May 22, 2014
.Dt URL-TOOL \&1 "GO-CAMO MANUAL"
.Os GO-CAMO VERSION
.Sh NAME
.Nm url-tool 
.Nd provides a simple way to generate signed URLs from the command line 
.Sh SYNOPSIS
.Nm url-tool
.Oo
.Em OPTIONS Ns 
.Oc
.Oo
.Em OPTION-ARGUMENTS Ns 
.Oc
.Sh DESCRIPTION
.Sy url-tool
provides a simple way to generate signed URLs from the command line
compatible with 
.Xr go-camo 1 .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl k Ns , Fl -key Ns = Ns Aq Ar hmac-key
The HMAC key to use.
.It Fl h Ns , Fl -help
Show help output and exit
.El
.Sh COMMANDS
url-tool has two subcommands.
.Bl -tag -width Ds
.It Cm encode Aq Ar url
.Pp
Available
.Cm encode
options:
.Bl -tag -width Ds
.It Fl b Ns , Fl -base Ns = Ns Aq Ar base
The base encoding to use. Can be one of 
.Em hex
or 
.Em base64 Ns  .
.It Fl -prefix Ns = Ns Aq Ar prefix
Optional url prefix used by encode output.
.El
.It Cm decode Aq Ar url
.El
.Sh EXAMPLES
Encode a url as hex:
.Bd -literal
 $ ./url-tool -k "test" encode -p "https://img.example.org" "http://golang.org/doc/gopher/frontpage.png"
 https://img.example.org/0f6def1cb147b0e84f39cbddc5ea10c80253a6f3/687474703a2f2f676f6c616e672e6f72672f646f632f676f706865722f66726f6e74706167652e706e67
.Ed
.Pp
Encode a url as base64:
.Bd -literal
 $ ./url-tool -k "test" encode -b base64 -p "https://img.example.org" "http://golang.org/doc/gopher/frontpage.png"
 https://img.example.org/D23vHLFHsOhPOcvdxeoQyAJTpvM/aHR0cDovL2dvbGFuZy5vcmcvZG9jL2dvcGhlci9mcm9udHBhZ2UucG5n
.Ed
.Pp
Decode a hex url:
.Bd -literal
 $ ./url-tool -k "test" decode "https://img.example.org/0f6def1cb147b0e84f39cbddc5ea10c80253a6f3/687474703a2f2f676f6c616e672e6f72672f646f632f676f706865722f66726f6e74706167652e706e67"
 http://golang.org/doc/gopher/frontpage.png
.Ed
.Pp
Decode a base64 url:
.Bd -literal
 $ ./url-tool -k "test" decode "https://img.example.org/D23vHLFHsOhPOcvdxeoQyAJTpvM/aHR0cDovL2dvbGFuZy5vcmcvZG9jL2dvcGhlci9mcm9udHBhZ2UucG5n"
 http://golang.org/doc/gopher/frontpage.png
.Ed
.Sh WWW
https://github.com/cactus/go-camo
