// Copyright (c) 2012-2016 Eli Janssen
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

package main

const licenseText = `
This software is available under the MIT License at:
└── https://github.com/cactus/go-camo

Portions of this software utilize third party libraries:
├── https://github.com/cactus/gologit           (MIT License)
├── https://github.com/jessevdk/go-flags        (BSD License)
└── github.com/stretchr/testify/assert          (MIT License)
    ├── https://github.com/davecgh/go-spew      (ISC License)
    └── https://github.com/pmezard/go-difflib   (BSD License)
`