// Copyright (c) 2012-2018 Eli Janssen
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

package main

const licenseText = `
This software is available under the MIT License at:
https://github.com/cactus/go-camo

Portions of this software utilize third party libraries:
*   Runtime dependencies:
    ├── github.com/cactus/mlog (MIT license)
    └── github.com/jessevdk/go-flags (BSD license)

*   Test/Build only dependencies:
    ├── github.com/stretchr/testify (MIT license)
    └── github.com/pelletier/go-toml (MIT license)

`